WavPack support, using versions 4.x and 5.x of the wavpack library.
NOTES / TODO:

* DSD files loading is disabled for the moment: needs special care.

* Hybrid mode file support: For correction file (*.wvc) discovery:
  - the file must be loaded with Mix_LoadMUS, not Mix_LoadMUS_RW,
  - Mix_Init must be called with MIX_INIT_WAVPACK flag, beforehand.
  Otherwise, the file will be decoded in lossy mode, not lossless.

* Channel mapping corrections _might_ (or might not) be needed for
  wavpack files with more than 2 channels.

- Dynamic loading of windows wavpack dlls named 'wavpackdll.dll'
  (as available from official wavpack site) is not coded in cmake
  and autotools build systems.  It shall need manually specifying
  with the WAVPACK_DYNAMIC macro define, if really wanted.

Co-authored-by: Anonymous Maarten <anonymous.maarten@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -800,6 +800,7 @@ ac_includes_default="\
 ac_header_c_list=
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
+SDL2MIXER_WAVPACK
 SDL2MIXER_WAVE
 SDL2MIXER_VORBIS_VORBISFILE
 SDL2MIXER_VORBIS_TREMOR
@@ -831,6 +832,8 @@ VERSION_OBJECTS
 OBJECTS
 ac_aux_dir
 cmake_prefix_relpath
+WAVPACK_LIBS
+WAVPACK_CFLAGS
 OPUSFILE_LIBS
 OPUSFILE_CFLAGS
 MPG123_LIBS
@@ -994,6 +997,8 @@ enable_music_mp3_mpg123
 enable_music_mp3_mpg123_shared
 enable_music_opus
 enable_music_opus_shared
+enable_music_wavpack
+enable_music_wavpack_shared
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1027,7 +1032,9 @@ FLAC_LIBS
 MPG123_CFLAGS
 MPG123_LIBS
 OPUSFILE_CFLAGS
-OPUSFILE_LIBS'
+OPUSFILE_LIBS
+WAVPACK_CFLAGS
+WAVPACK_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1706,6 +1713,9 @@ Optional Features:
   --enable-music-opus     enable Opus music [default=yes]
   --enable-music-opus-shared
                           dynamically load opusfile library [default=yes]
+  --enable-music-wavpack  enable WavPack music [default=yes]
+  --enable-music-wavpack-shared
+                          dynamically load WavPack library [default=yes]
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1761,6 +1771,10 @@ Some influential environment variables:
               C compiler flags for OPUSFILE, overriding pkg-config
   OPUSFILE_LIBS
               linker flags for OPUSFILE, overriding pkg-config
+  WAVPACK_CFLAGS
+              C compiler flags for WAVPACK, overriding pkg-config
+  WAVPACK_LIBS
+              linker flags for WAVPACK, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -4936,13 +4950,13 @@ then :
 else $as_nop
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4939: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4953: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4942: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4956: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4945: output\"" >&5)
+  (eval echo "\"\$as_me:4959: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6201,7 +6215,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6204 "configure"' > conftest.$ac_ext
+  echo '#line 6218 "configure"' > conftest.$ac_ext
   if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_compile\""; } >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7874,11 +7888,11 @@ else $as_nop
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7877: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7891: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7881: \$? = $ac_status" >&5
+   echo "$as_me:7895: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8224,11 +8238,11 @@ else $as_nop
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8227: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8241: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8231: \$? = $ac_status" >&5
+   echo "$as_me:8245: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8331,11 +8345,11 @@ else $as_nop
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8334: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8348: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8338: \$? = $ac_status" >&5
+   echo "$as_me:8352: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8387,11 +8401,11 @@ else $as_nop
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8390: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8404: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8394: \$? = $ac_status" >&5
+   echo "$as_me:8408: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10830,7 +10844,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10833 "configure"
+#line 10847 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10927,7 +10941,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10930 "configure"
+#line 10944 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14626,11 +14640,11 @@ else $as_nop
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14629: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14643: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14633: \$? = $ac_status" >&5
+   echo "$as_me:14647: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14727,11 +14741,11 @@ else $as_nop
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14730: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14744: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14734: \$? = $ac_status" >&5
+   echo "$as_me:14748: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14780,11 +14794,11 @@ else $as_nop
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14783: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14797: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14787: \$? = $ac_status" >&5
+   echo "$as_me:14801: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19059,6 +19073,256 @@ printf "%s\n" "$as_me: WARNING: Opus support disabled" >&2;}
     fi
 fi
 
+SDL2MIXER_WAVPACK=0
+# Check whether --enable-music-wavpack was given.
+if test ${enable_music_wavpack+y}
+then :
+  enableval=$enable_music_wavpack;
+else $as_nop
+  enable_music_wavpack=yes
+fi
+
+# Check whether --enable-music-wavpack-shared was given.
+if test ${enable_music_wavpack_shared+y}
+then :
+  enableval=$enable_music_wavpack_shared;
+else $as_nop
+  enable_music_wavpack_shared=yes
+fi
+
+if test x$enable_music_wavpack = xyes; then
+    LIBS_SAVED="$LIBS"
+
+pkg_failed=no
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for wavpack >= 4.0" >&5
+printf %s "checking for wavpack >= 4.0... " >&6; }
+
+if test -n "$WAVPACK_CFLAGS"; then
+    pkg_cv_WAVPACK_CFLAGS="$WAVPACK_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"wavpack >= 4.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "wavpack >= 4.0") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_WAVPACK_CFLAGS=`$PKG_CONFIG --cflags "wavpack >= 4.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$WAVPACK_LIBS"; then
+    pkg_cv_WAVPACK_LIBS="$WAVPACK_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"wavpack >= 4.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "wavpack >= 4.0") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_WAVPACK_LIBS=`$PKG_CONFIG --libs "wavpack >= 4.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        WAVPACK_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "wavpack >= 4.0" 2>&1`
+        else
+	        WAVPACK_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "wavpack >= 4.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$WAVPACK_PKG_ERRORS" >&5
+
+	            ac_fn_c_check_header_compile "$LINENO" "wavpack.h" "ac_cv_header_wavpack_h" "$ac_includes_default"
+if test "x$ac_cv_header_wavpack_h" = xyes
+then :
+  have_wavpack_hdr=yes;have_wavpack_hdr2=yes
+fi
+
+            ac_fn_c_check_header_compile "$LINENO" "wavpack/wavpack.h" "ac_cv_header_wavpack_wavpack_h" "$ac_includes_default"
+if test "x$ac_cv_header_wavpack_wavpack_h" = xyes
+then :
+  have_wavpack_hdr=yes
+fi
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for WavpackOpenFileInputEx in -lwavpack" >&5
+printf %s "checking for WavpackOpenFileInputEx in -lwavpack... " >&6; }
+if test ${ac_cv_lib_wavpack_WavpackOpenFileInputEx+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lwavpack -lm $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+char WavpackOpenFileInputEx ();
+int
+main (void)
+{
+return WavpackOpenFileInputEx ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"
+then :
+  ac_cv_lib_wavpack_WavpackOpenFileInputEx=yes
+else $as_nop
+  ac_cv_lib_wavpack_WavpackOpenFileInputEx=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_wavpack_WavpackOpenFileInputEx" >&5
+printf "%s\n" "$ac_cv_lib_wavpack_WavpackOpenFileInputEx" >&6; }
+if test "x$ac_cv_lib_wavpack_WavpackOpenFileInputEx" = xyes
+then :
+  have_wavpack_lib=yes;WAVPACK_LIBS="-lwavpack"
+fi
+
+
+elif test $pkg_failed = untried; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+	            ac_fn_c_check_header_compile "$LINENO" "wavpack.h" "ac_cv_header_wavpack_h" "$ac_includes_default"
+if test "x$ac_cv_header_wavpack_h" = xyes
+then :
+  have_wavpack_hdr=yes;have_wavpack_hdr2=yes
+fi
+
+            ac_fn_c_check_header_compile "$LINENO" "wavpack/wavpack.h" "ac_cv_header_wavpack_wavpack_h" "$ac_includes_default"
+if test "x$ac_cv_header_wavpack_wavpack_h" = xyes
+then :
+  have_wavpack_hdr=yes
+fi
+
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for WavpackOpenFileInputEx in -lwavpack" >&5
+printf %s "checking for WavpackOpenFileInputEx in -lwavpack... " >&6; }
+if test ${ac_cv_lib_wavpack_WavpackOpenFileInputEx+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lwavpack -lm $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+char WavpackOpenFileInputEx ();
+int
+main (void)
+{
+return WavpackOpenFileInputEx ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"
+then :
+  ac_cv_lib_wavpack_WavpackOpenFileInputEx=yes
+else $as_nop
+  ac_cv_lib_wavpack_WavpackOpenFileInputEx=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_wavpack_WavpackOpenFileInputEx" >&5
+printf "%s\n" "$ac_cv_lib_wavpack_WavpackOpenFileInputEx" >&6; }
+if test "x$ac_cv_lib_wavpack_WavpackOpenFileInputEx" = xyes
+then :
+  have_wavpack_lib=yes;WAVPACK_LIBS="-lwavpack"
+fi
+
+
+else
+	WAVPACK_CFLAGS=$pkg_cv_WAVPACK_CFLAGS
+	WAVPACK_LIBS=$pkg_cv_WAVPACK_LIBS
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+	            have_wavpack_hdr=yes
+            have_wavpack_lib=yes
+            have_wavpack_pc=yes
+
+fi
+    if test x$have_wavpack_pc = xyes; then
+        CFLAGS_SAVED="$CFLAGS"
+        CFLAGS="$CFLAGS $WAVPACK_CFLAGS"
+        ac_fn_c_check_header_compile "$LINENO" "wavpack.h" "ac_cv_header_wavpack_h" "$ac_includes_default"
+if test "x$ac_cv_header_wavpack_h" = xyes
+then :
+  have_wavpack_hdr2=yes
+fi
+
+        CFLAGS="$CFLAGS_SAVED"
+    fi
+    LIBS="$LIBS_SAVED"
+
+    if test x$have_wavpack_hdr = xyes -a x$have_wavpack_lib = xyes; then
+        have_wavpack=yes
+        case "$host" in
+            *-*-darwin*)
+                wavpack_lib=`find_lib libwavpack.dylib`
+                ;;
+            *-*-cygwin* | *-*-mingw*)
+                wavpack_lib=`find_lib "libwavpack*.dll"`
+                ;;
+            *)
+                wavpack_lib=`find_lib "libwavpack[0-9]*.so.*"`
+                if test x$wavpack_lib = x; then
+                    wavpack_lib=`find_lib "libwavpack.so.*"`
+                fi
+                ;;
+        esac
+        EXTRA_CFLAGS="$EXTRA_CFLAGS -DMUSIC_WAVPACK $WAVPACK_CFLAGS"
+        if test x$have_wavpack_hdr2 = xyes; then
+            EXTRA_CFLAGS="$EXTRA_CFLAGS -DHAVE_WAVPACK_H"
+        fi
+        if test x$enable_music_wavpack_shared = xyes && test x$wavpack_lib != x; then
+            echo "-- dynamic wavpack -> $wavpack_lib"
+            EXTRA_CFLAGS="$EXTRA_CFLAGS -DWAVPACK_DYNAMIC=\\\"$wavpack_lib\\\""
+        else
+            MIXER_LIBS="$MIXER_LIBS $WAVPACK_LIBS"
+            if test x$have_wavpack_pc = xyes; then
+                PC_REQUIRES="$PC_REQUIRES wavpack"
+            else
+                PC_LIBS="$PC_LIBS $WAVPACK_LIBS"
+            fi
+        fi
+        SDL2MIXER_WAVPACK=1
+    else
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: *** Unable to find WavPack library (http://www.wavpack.com)" >&5
+printf "%s\n" "$as_me: WARNING: *** Unable to find WavPack library (http://www.wavpack.com)" >&2;}
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: WavPack support disabled" >&5
+printf "%s\n" "$as_me: WARNING: WavPack support disabled" >&2;}
+    fi
+fi
+
 CheckNoUndef
 
 MIXER_LIBS="$MIXER_LIBS $LIBM"
@@ -19199,6 +19463,7 @@ case "$_lcl_notation" in
 esac
   eval $_lcl_result_var='$_lcl_result_tmp'
 done
+
 
 
 
